### ISSUE TITLE
A fresh clone is missing a lot of stuff.

### ISSUE THREAD

**Issue by jaseemabid** [pranavashok/Avhtat#1]
Seems like a lot of files (graphic ) mainly is not tracked. feels like stuff missing. Please checkout a new clone and make sure this is what you want.

**Comment by shamilcm** [comment]
What does files "not tracked" mean?

On Fri, Jul 22, 2011 at 1:22 AM, jaseemabid <
reply@reply.github.com>wrote:

> Seems like a lot of files (graphic ) mainly is not tracked. feels like
> stuff missing. Please checkout a new clone and make sure this is what you
> want.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/pranavashok/Tathva--11-Website/issues/1

## 

Shamil C. M.
B. Tech | Computer Science & Engineering
NIT Calicut
+91-996-105-6990

**Comment by pranavashok** [comment]
If I'm right, it means those files aren't present. But I can't see any problem like that. Jaseem, can you recheck?

**Comment by jaseemabid** [comment]
I meant stuff like the side doc and the huge black box in top right corner. do you have something in it or is it left empty ?

**Comment by pranavashok** [comment]
It's left empty.
